[package]
name = "offchain-client"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
subxt = "0.34.0"
subxt-signer = "0.34.0"
tokio = { version = "1.36.0", features = ["rt-multi-thread"] }
